[package]
name = "genealogy"
version = "0.1.0"
authors = ["Max Bruckner <max@maxbruckner.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
debug_stub_derive = "0.3"
directories = "3"
futures = {version = "0.3", default_features = false, features = ['async-await']}
lazy_static = "1"
parking_lot = "0.11"
regex = "1"
resiter = "0.4"
tokio = {version = "0.3", features = ['fs', 'io-util', 'stream']}
url = "2"

[dev-dependencies]
literally = "0.1.3"
