#![allow(clippy::tabs_in_doc_comments)]
pub mod collection;
pub mod collector;
pub mod comparator;
pub mod completable_future;
pub mod exception;
pub mod files;
pub mod indexing;
pub mod integer;
pub mod iterator;
pub mod list;
pub mod map;
pub mod objects;
pub mod optional;
pub mod path;
pub mod process_handle;
pub mod runtime;
pub mod service_loader;
pub mod set;
pub mod r#static;
pub mod stream;
pub mod string;
pub mod system;
pub mod test;
pub mod time;
pub mod uri;

pub use genealogy_macros::record;
pub use lazy_static::lazy_static;
